{{- if and .Values.mongodb.prometheus.enabled .Values.serviceMonitor.enabled (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "mongodbcommunity.mongodbcommunity.mongodb.com") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mongodb-community-database.fullname" . }}
  labels:
    {{- include "mongodb-community-database.labels" . | nindent 4 }}
spec:
  endpoints:
    - basicAuth:
        password:
          key: password
          name: {{ include "mongodb-community-database.fullname" . }}-metrics-endpoint
        username:
          key: username
          name: {{ include "mongodb-community-database.fullname" . }}-metrics-endpoint-password
      port: prometheus
      scheme: http
      interval: {{ .Values.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | quote }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 4 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 4 }}
      {{- end }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-svc"
{{- end }}
