apiVersion: v2
name: mongodb-community-database
icon: https://images.contentstack.io/v3/assets/blt7151619cb9560896/blta30d0168850404a8/65fda6758f44440029c3a12a/la1a1agcxt7ppntea-logo-marks.svg
description: A Helm chart to deploy CR MongoDB Community database
type: application
maintainers:
  - name: ialejandro
    email: hello@ialejandro.rocks
    url: https://ialejandro.rocks
sources:
  - https://github.com/devops-ia/helm-mongodb-community-database
  - https://github.com/mongodb/helm-charts/tree/main/charts/community-operator-crds
version: 1.0.0
appVersion: "8.0.6-ubi9"
home: https://github.com/devops-ia/helm-mongodb-community-database
keywords:
  - chart
  - mongodb
  - kubernetes
  - database
